INSERT INTO TB_CATEGORY (NAME) VALUES ('Eletronics');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Livros');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Computers');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Iphone');
INSERT INTO TB_CATEGORY (NAME) VALUES ('calcados');
INSERT INTO TB_CATEGORY (NAME) VALUES ('fastfood');
INSERT INTO TB_CATEGORY (NAME) VALUES ('unhas');
INSERT INTO TB_CATEGORY (NAME) VALUES ('infantil');